version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm start"
    volumes:
      - .:/quantum
    ports:
      - "3000:3000"
    environment:
      - API_HOST=192.168.33.10
